package us.randos.very_serious_steven;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class VerySeriousStevenConstants {

	public static final String VERY_SERIOUS_MOD_ID_FOR_THE_COOLEST_MOD_IN_EXISTENCE_NAMED_VERY_SERIOUS_STEVEN_MOD_FOR_THE_KAUPENHUB_SERVER = "very_serious_steven";
	public static final String VERY_SERIOUS_MOD_NAME_FOR_THE_COOLEST_MOD_IN_EXISTENCE_NAMED_VERY_SERIOUS_STEVEN_MOD_FOR_THE_KAUPENHUB_SERVER = "Very Serious Steven";
	public static final Logger LOGGER = LoggerFactory.getLogger(VERY_SERIOUS_MOD_NAME_FOR_THE_COOLEST_MOD_IN_EXISTENCE_NAMED_VERY_SERIOUS_STEVEN_MOD_FOR_THE_KAUPENHUB_SERVER);
}